### ISSUE TITLE
Not showing signature confirmations

### ISSUE THREAD

**Issue by jstarry** [solana-labs/explorer#10]
Blocked on https://github.com/solana-labs/solana/pull/9138 being released

#### Problem
The explorer needs to know which slot a particular transaction was added to and how many confirmations that slot has. 

#### Proposed Solution
Wait for RPC update to get necessary information

**Comment by jstarry** [comment]
@CriesofCarrots @mvines does this proposed solution look ok?

**Comment by CriesofCarrots** [comment]
When will you unsubscribe for missing statuses? After 32 new roots?

**Comment by jstarry** [comment]
Hmm sounds reasonable. I think never unsubscribing should be fine too in case someone is waiting for a particular transaction for an extended period of a time
