### ISSUE TITLE
Can't see that locked up stake accounts aren't part of circulating supply

### ISSUE THREAD

**Issue by garious** [solana-labs/explorer#107]
#### Problem

When viewing an account, there's no indication that it is locked up and therefore not part of the circulating supply.

#### Proposed Solution

Add an indicator, perhaps in an "Account Details" dialog. Something that mimics the information currently available in the output of `solana stake-account <ACCOUNT_ADDRESS>`.

**Comment by jstarry** [comment]
@garious this info in the "Account Details" *page* now, is that sufficient?

**Comment by garious** [comment]
Yep, thanks so much!
