### ISSUE TITLE
Make transactions in an account transaction history clickable

### ISSUE THREAD

**Issue by mvines** [solana-labs/explorer#114]
I looked up an account and found a transaction,
![image](https://user-images.githubusercontent.com/1281082/81960813-5cba5500-95c6-11ea-810f-81df393d6310.png)

but now I need to copy-n-paste that `5pWRMSRP2vBkWo238B557VujNqcGM4A122dHqvVCM77QeAx3e7b9DVhbZuFdq7fqEMK4MNFD5RQX8qpXAaTVFXgA` into a different part of the explorer to view it.  Ideally there'd be an inline button or link that takes me to the transaction details

**Comment by jstarry** [comment]
Related to: https://github.com/solana-labs/explorer/issues/66
