### ISSUE TITLE
Copy tooltips cutoff, not copying

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/explorer#120]
There are lots of things in the Account and Transaction details screens that pop up a "Copy" tooltip on hover.

1. The copy-on-click doesn't actually seem to copy anything to clipboard; Firefox 76 and Chrome 81, macOS
2. The tooltip gets cutoff by some content frames:
![image](https://user-images.githubusercontent.com/3030561/82252331-0faee980-990c-11ea-9b6e-ef9229374296.png)

**Comment by jstarry** [comment]
@CriesofCarrots I'm unable to repro the broken copy-on-click issue. I'm also on macOS and the same firefox/chrome versions

**Comment by jstarry** [comment]
@CriesofCarrots I just found out that clipboard support isn't enabled on http, https is required. I think that's probably what you were running into

**Comment by CriesofCarrots** [comment]
> I just found out that clipboard support isn't enabled on http, https is required.
Wow, good detective work @jstarry , thanks for following up! I wonder how I ended up on http; I'll keep an eye on all our links into the explorer.
