### ISSUE TITLE
Cache supply adjustment transactions in explorer codebase

### ISSUE THREAD

**Issue by ericlwilliams** [solana-labs/explorer#139]
#### Problem
Currently, explorer transaction data persists for ~30 days. We would like to persist transactions related to the recent supply adjustment.
#### Proposed Solution
Cache the following six transactions in explorer codebase for persistent retrieval.

uQf4pS38FjRF294QFEXizhYkZFjSR9ZSBvvV6MV5b4VpdfRnK3PY9TWZ2qHMQKtte3XwKVLcWqsTF6wL9NEZMty
DYrfStEEzbV5sftX8LgUa54Nwnc5m5E1731cqBtiiC66TeXgKpfqZEQTuFY3vhHZ2K1BsaFM3X9FqisR28EtZr8
3bLx2PLpkxCxJA5P7HVe8asFdSWXVAh1DrxfkqWE9bWvPRxXE2hqwj1vuSC858fUw3XAGQcHbJknhtNdxY2sehab
3fE8xNgyxbwbvA5MX3wM87ahDDgCVEaaMMSa8UCWWNxojaRYBgrQyiKXLSxcryMWb7sEyVLBWyqUaRWnQCroSqjY
5PWymGjKV7T1oqeqGn139EHFyjNM2dnNhHCUcfD2bmdj8cfF95HpY1uJ84W89c4sJQnmyZxXcYrcjumx2jHUvxZQ
5K4KuqTTRNtzfpxWiwnkePzGfsa3tBEmpMy7vQFR3KWFAZNVY9tvoSaz1Yt5dKxcgsZPio2EsASVDGbQB1HvirGD

**Comment by jstarry** [comment]
@ericlwilliams @mvines these transactions aren't available anymore from the API. Do you have the info handy?

**Comment by ericlwilliams** [comment]
@jstarry I'll share a doc with you on slack.

**Comment by mvines** [comment]
That's surprising because:
```
$ $ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"minimumLedgerSlot"}' http://api.mainnet-beta.solana.com
{"jsonrpc":"2.0","result":7665164,"id":1}
```
and those transactions aren't that old

**Comment by mvines** [comment]
For example:
```
Slot: 10440804
Recent Blockhash: 5Aw8MaMYdYtnfJyyrregWMWGgiMtWZ6GtRzeP6Ufo65Z
Signature 0: uQf4pS38FjRF294QFEXizhYkZFjSR9ZSBvvV6MV5b4VpdfRnK3PY9TWZ2qHMQKtte3XwKVLcWqsTF6wL9NEZMty
MessageHeader { num_required_signatures: 1, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 1 }
Account 0: 2ojv9BAiHUrvsm9gxDe7fJSzbNZSJcxZvf8dqmWGHG8S
Account 1: 4C6NCcLPUgGuBBkV2dJW96mrptMUCp3RG1ft9rqwjFi9
Account 2: 11111111111111111111111111111111
Instruction 0
  Program: 11111111111111111111111111111111 (2)
  Account 0: 2ojv9BAiHUrvsm9gxDe7fJSzbNZSJcxZvf8dqmWGHG8S (0)
  Account 1: 4C6NCcLPUgGuBBkV2dJW96mrptMUCp3RG1ft9rqwjFi9 (1)
  Transfer { lamports: 100000000000 }
Status: Ok
  Fee: 0.000005 SOL
  Account 0 balance: 13535368.645204201 SOL -> 13535268.645199202 SOL
  Account 1 balance: 0 SOL -> 100 SOL
  Account 2 balance: 0.000000001 SOL
```

**Comment by mvines** [comment]
The missing transaction history were a side-effect of the mainnet-beta restart and the lack of https://github.com/solana-labs/solana/pull/10358 on v1.1.

We do in fact have these transactions in the RPC node ledger still

**Comment by jstarry** [comment]
@mvines I tried using the ledger-tool to print slot 10440804 and I get a blockstore error:

> Failed to load entries for slot 10440804: blockstore error

Did anything change since you queried earlier?

**Comment by jstarry** [comment]
Nvm, I see the conversation in #sdk now!
