### ISSUE TITLE
Mint Refresh does not update holders nor holders' token amounts

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/explorer#169]
1) 

- **Expected**
1 Create a new mint on mainnet-beta and open its page in the explorer 2. init an account for the mint 3. press refresh button on mint page 4. now the token holders of the mint includes the newly created account

- **Actual**
1 Create a new mint on mainnet-beta and open its page in the explorer 2. init an account for the mint 3. press refresh button on mint page 4. **no new account is shown**

2) 

- **Expected**
1 Create a new mint on mainnet-beta and open its page in the explorer 2. init an account for the mint 3. reload the page (because of 1)) 4. mint to the newly created account 5. press refresh button on mint page 6. explorer now shows updated holders' token amounts
- **Actual**
1 Create a new mint on mainnet-beta and open its page in the explorer 2. init an account for the mint 3. reload the page (because of 1)) 4. mint to the newly created account 5. press refresh button on mint page 6. **explorer does not show updated holders' token amounts**

**Comment by jstarry** [comment]
@paul-schaaf before I dig into this, can you let me know if you waited ~20s before refreshing? Any account changes have to be confirmed before they show up in the explorer. If you refresh right after the transaction, it won't show up

**Comment by paul-schaaf** [comment]
@jstarry I didnt know I had to do that, maybe that info could be added somewhere in the explorer? That said, I did wait for 20 seconds now and that didn't fix it.

**Comment by jstarry** [comment]
No worries, thanks for checking. I'd like to fix this by adding a refresh button here. Does that solve your issue?
![Screen Shot 2020-10-21 at 4 29 25 PM](https://user-images.githubusercontent.com/1076145/96694138-a3547c80-13ba-11eb-8e9a-f5401d1bbfe5.png)

**Comment by paul-schaaf** [comment]
is there a need for another button? Why not let the existing refresh button refresh account holders and their balances correctly? @jstarry

**Comment by jstarry** [comment]
Not really a need, just convention I had been using. Agreed that existing refresh button should control it
