### ISSUE TITLE
Explorer accessing inaccessible token list

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/explorer#199]
Explorer accesses this on startup:

```
https://token-list.solana.com/solana.tokenlist.json
```

That endpoint is down.

**Comment by steveluscher** [comment]
@jacobcreech @jnwng is it time to take token-list.solana.com down, and delete it from Heroku?

**Comment by jacobcreech** [comment]
How long has it been down? Probably time to move over to [unified token list](https://github.com/solana-labs/solana/issues/26524)

**Comment by steveluscher** [comment]
No idea. I can't see logs older than 24 hours, so probably forever.

**Comment by jacobcreech** [comment]
Haven't heard any complaints at this time on my side. Seems like it may be time to move

**Comment by steveluscher** [comment]
What do you mean by move? Move the app (I literally don't even know what we're talking about) or move on deleting it?

**Comment by steveluscher** [comment]
OH. Move over to the modern thing. Got it.
