### ISSUE TITLE
Explorer OOMs when loading homepage on testnet

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/explorer#200]
Repro:

1. Load https://explorer.solana.com/?cluster=testnet

Observe that browser runs out of memory. Seems to keep calling a combination of `buildTicks`, `update`, and `_convertTicksToLabels`, `measureText` and `_getLabelSizes` until it runs out of memory.

Here's a Chrome profile that you can load into the profiler: https://drive.google.com/file/d/1r_NAkpul0kZ7f_nU72T6h4CIlyWlozl4/view?usp=share_link

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13243/218480184-1776b218-fd55-4c32-942b-02297cc7b57d.png">

**Comment by ngundotra** [comment]
It's definitely from `TpsCardBody`, but not sure if it's from excessive chart rendering or an abuse of network calls
