### ISSUE TITLE
[Bug] Site crashes with `Application error` while trying to use transaction inspector

### ISSUE THREAD

**Issue by KartikSoneji** [solana-labs/explorer#265]
**Describe the bug**
Trying to use the transaction inspector at `/tx/inspector` results in the following error:
message: `Application error: a client-side exception has occurred (see the browser console for more information).`
stacktrace:
```
Error: useFetchAccountInfo must be used within a AccountsProvider
    at eG (1603-bf22ea245bb1a13e.js:1:12745)
    at es (1401-00ed260fdd1ff68b.js:1:21124)
    at rs (aafedb4d-dc1b172440158775.js:9:38883)
    at iv (aafedb4d-dc1b172440158775.js:9:111743)
    at oR (aafedb4d-dc1b172440158775.js:9:90032)
    at aafedb4d-dc1b172440158775.js:9:89881
    at oD (aafedb4d-dc1b172440158775.js:9:89888)
    at ow (aafedb4d-dc1b172440158775.js:9:87590)
    at nJ (aafedb4d-dc1b172440158775.js:9:36784)
    at oz (aafedb4d-dc1b172440158775.js:9:88649)
    at io (aafedb4d-dc1b172440158775.js:9:117483)
    at sn (aafedb4d-dc1b172440158775.js:9:134985)
    at i9 (aafedb4d-dc1b172440158775.js:9:124577)
    at i5 (aafedb4d-dc1b172440158775.js:9:124367)
    at HTMLDocument.f (5956-d85804bcda78da32.js:1:152386)
```

**To Reproduce**
1. Go to https://explorer.solana.com/tx/inspector
2. Paste in a serialized tx
3. Observe error message
4. Open console

**Example Links**

-   [example tx](https://explorer.solana.com/tx/inspector?signatures=%255B%25221111111111111111111111111111111111111111111111111111111111111111%2522%255D&message=AQAOGY6P4PPkduz%252B8cGI2lSd284qg%252BteyYGdNMjwAUy5oJTcKv4cJCAqWPznXkInKnwG0SRRPvlMf4Z23GMj87fy5ldXwzXfi6Y7XsXhWaEBUcotFUTlZjRzoZS8Sh%252FkR9nDV20VlwJvt5qX2AU77I4LQLVnCEgji9%252BG9tf9lG4rQSZNb9q0sLYksNzq01Cl4hfuuj4SRznKiLol5diLFbq6NV%252Bdtq8Kb6Cs508JSarJqYlOeSKHoKUU6wAN0NHCUW%252BsbsRbKAa07kld6fMfhk83LvirncIMMBWRfgNNaIDVZhe1ziQihycl3c1XO%252FLAvROoyPcgyXjzhljGWueWZR4OAlbHvc%252FhIY6mrbjHKyaAmxdhs3JvyYvPHH3jJTAsAKVI0s64UyBvFpYAJyV8BEd0QmjrWcLny%252BSO6lt9QqNcHBOc4SNPjX10wqyIjC3Q372ySB%252BamzgoErJZ365UwzqlD8cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACtVHrtVhyribMnCf4V%252Ft3MdT%252FyRJSYAddc7h%252FYDk%252Fq7ThkvWWlLmNpD%252FrtbjYzUhu2%252BmGjHC%252BxYq2xfIBBTlkZZvdHDWtyymPVf6VxYZinM9DllI0zftSzzRU%252B4Z3cEQmiEvwusZJdGJS8IeRl%252FJmuWSKj6WzXzKjXUi4AO%252BEcAjJclj04kifG7PRApFI4NgwtaE5na%252FxCEBI572Nvp%252BFmxV%252B95njQ1nX4TqquHgG9sQxg%252FZWCUyHA9cTMlnvXS7N1ikNBEuIwB%252F9MIn3HSz3XCg5%252FLSAvDQz%252BC9oTzeAURCmWThjy6RhVk6uQTc3IVRusBUckwgna71K0qHDpCEHv0JF6XdZMSX7FZQbbAqSYK9EOLzRA1UpKkCwXfh%252FXVIAuxtdQOT6iste2ZYfITUcSiFoUZzPsWwL6WJkZZac7KBpuIV%252F6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAEGp9UXGSxcUSGMyUw9SvF%252FWNruCJuh%252FUTj29mKAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV%252B%252FwCpdsxvfqcyo2X0V4RsehcQCW9N88zxobWGU%252FO23zyhhS4CEAYABAENCxgAFRoTAwEACQ0OFgoABBIPBQgCBwYMERgLEBQXABwlStmdTzEjBv3%252F%252F%252F4Ao%252BERAAAAAAEAAAAAAAAA)

**Expected behavior**
Site should not crash.

**Screenshots**
![image](https://github.com/solana-labs/explorer/assets/25801283/bf690e08-a4e7-4597-ba22-1c3409c6cf28)

**Comment by mcintyre94** [comment]
Sorry about this and thanks for reporting it! Will get this fixed now, it's an accidental result of a change I made yesterday.

**Comment by mcintyre94** [comment]
Fixed now, eg. https://explorer.solana.com/tx/5ojMiepv7YEr6Y5WkpqyZBFuN49d9LrN2NXsgKCAQYbS2GwxUhv4KwKc6Y7vE8cannanZ8LR13JYtqW36a5FMEqT/inspect
