### ISSUE TITLE
[Bug] Token distribution UI doesn't work, RPC won't fetch accounts

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/explorer#269]
**Describe the bug**

The token distribution tab makes an RPC call to `getTokenLargestAccounts. It gets an error response:
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32010,
        "message": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA excluded from account secondary indexes; this RPC method unavailable for key"
    },
    "id": "fdc6addf-3166-4169-8dac-85ec88b5672d"
}
```

The "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA excluded" suggests that this will error for all tokens, it's not particular to the token being loaded. And this seems to be the case, all tokens I've checked on mainnet give a similar response.

This results in the UI displaying that the largest accounts failed to load. 

**To Reproduce**

Go to https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/largest
See Distribution tab

Note that devnet works correctly, eg: https://explorer.solana.com/address/GqGn2LFgZYLhjikiSYW6Q4w26JXxnxBRuNMFmT3MjB6M/largest?cluster=devnet 

**Example Links**

-  mainnet (USDC, error): https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/largest
- mainnet (Orca, error): https://explorer.solana.com/address/orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE/largest
- devnet (works): https://explorer.solana.com/address/GqGn2LFgZYLhjikiSYW6Q4w26JXxnxBRuNMFmT3MjB6M/largest?cluster=devnet 

**Expected behavior**

The RPC should return the largest token accounts and the UI should display them

**Screenshots**

<img width="1154" alt="Screenshot 2023-07-12 at 14 58 23" src="https://github.com/solana-labs/explorer/assets/1711350/4ec021fd-d245-4396-b7f3-64c7491b4cc2">

**Comment by ngundotra** [comment]
this is an RPC error, flagged to partners @mcintyre94

**Comment by mcintyre94** [comment]
Closing, looks like we already found this bug and planned to remove the panel: https://github.com/solana-labs/explorer/issues/210

That'll also simplify #268 where I hit this so win/win

**Comment by steveluscher** [comment]
Yeah, Triton nerfed that call on purpose. It's too expensive.
