### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by bernieblume** [solana-labs/explorer#272]
Please add a LICENSE file. I assume this is meant to be Apache 2.0? I want to be legal when forking the repo...

**Comment by bernieblume** [comment]
@mvines is the explorer meant to be Apache 2.0 as well? If so, I can add the LICENSE file to this PR as well for easy merging... Currently, there is no LICENSE file at at all in the repo.

**Comment by mvines** [comment]
hey @steveluscher, can you please take this. I swear we did have a licens in package.json at one point.
I don't feel strong if we do MIT/BSD or Apache2, and the Copyright would be attributed to Solana Labs
