### ISSUE TITLE
[Bug] Anchor IDL not showing for program

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/explorer#316]
**Describe the bug**

A user asked on stackexchange why their anchor IDL doesn't show up on our Explorer: https://solana.stackexchange.com/questions/9569/idls-explorers-curiosity

Explorer link to their program: https://explorer.solana.com/address/propm845StqEBV57ZSnTe8EW8duzAxo5p7h4inhibXV?cluster=devnet

I took a look at Explorer and I think the code that fetches the IDL is this:

https://github.com/solana-labs/explorer/blob/5dcb64618bbbec58a4ec03ab2b8abe75ea92a19b/app/providers/anchor.tsx#L10-L37

I put a debugger on line 26 and viewed the reported program on devnet, and got an error "Tuple enum variants not yet implemented."
<img width="625" alt="Screenshot 2024-01-22 at 11 15 15" src="https://github.com/solana-labs/explorer/assets/1711350/8d1d6253-3a56-4fe2-ab71-b59515a65570">

Their IDL does work on solscan: https://solscan.io/account/propm845StqEBV57ZSnTe8EW8duzAxo5p7h4inhibXV?cluster=devnet#anchorProgramIDL

It also has a suspicious looking enum field:
<img width="848" alt="Screenshot 2024-01-22 at 11 22 47" src="https://github.com/solana-labs/explorer/assets/1711350/9a8cfcdb-4d8c-403b-9d9b-7fe420430ba9">

I'm guessing we need to update our version of Anchor to parse the newest IDLs

**To Reproduce**

1. Go to https://explorer.solana.com/address/propm845StqEBV57ZSnTe8EW8duzAxo5p7h4inhibXV?cluster=devnet, No Anchor IDL
2. Go to https://solscan.io/account/propm845StqEBV57ZSnTe8EW8duzAxo5p7h4inhibXV?cluster=devnet#anchorProgramIDL, Anchor IDL displays

**Example Links**

- https://explorer.solana.com/address/propm845StqEBV57ZSnTe8EW8duzAxo5p7h4inhibXV?cluster=devnet

**Expected behavior**

Show the Anchor IDL on this program!

**Comment by ngundotra** [comment]
Closed by #374
