### ISSUE TITLE
[Feature request] Add an explicit button for localhost 

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/explorer#326]
**Describe the ~bug~ feature**

**I know this may seem silly** but: a lot of experienced Solana developers (from our classes, Hacker Houses, etc)  genuinely have no idea that Solana Explorer can connect to localhost. Obviously there's 'Custom RPC URL' which defaults to localhost but **people simply don't realise it's there**.  😅

Proposing the UI add a button for this, so the list looks like:

 - The official mainnet-beta URL
 - The official devnet URL
 - The official testnet URL
 - The default CLI localhost URL
 - Then allow users to specify any other URL they like

Obviously this is a simple change I'm just writing this here to convince you to make it or let me send you a PR! 😁

![Screenshot 2024-04-01 at 12 16 36](https://github.com/solana-labs/explorer/assets/172594/543bdaec-3135-488a-b47f-a02bdd54a673)

**To Reproduce**

"Hey which of the well known addresses can Explorer connect to?"

"looks like mainnet-beta, devnet and testnet. I guess the 'Custom RPC' button is used to connect to mainnet-beta, devnet and testnet using a paid RPC provider like helius or Triton"

(months pass, get told you can actually use Explorer with localhost).

**Additional context**

Thanks for your consideration Noah! If you're busy I can make the PR too just LMK.

**Comment by ngundotra** [comment]
@mikemaccana by default, the Custom RPC Url will redirect back to localhost: see placeholder text

This should work 100% of time. If you're having issues using, ping me & we can debug

<img width="322" alt="Screenshot 2024-04-01 at 2 41 41 PM" src="https://github.com/solana-labs/explorer/assets/7481857/21220691-a73b-470a-aed3-d7d1a9f45c21">
