### ISSUE TITLE
Show toast error message when url parsing fails

### ISSUE THREAD

**Issue by jstarry** [solana-labs/explorer#38]
We need errors for:
* url contains invalid transaction signature
* url contains invalid account address

**Comment by nick-brown** [comment]
@jstarry Are there any more specific validation tests for transactions and accounts that I should be utilizing than these?:

- [TransactionsCard](https://github.com/solana-labs/explorer/blob/master/src/components/TransactionsCard.tsx#L21-L34)
- [AccountsCard](https://github.com/solana-labs/explorer/blob/master/src/components/AccountsCard.tsx#L26-L29)

**Comment by jstarry** [comment]
@nick-brown Here are the places I was referring to:
https://github.com/solana-labs/explorer/blob/82d5aa96354613e321152f32eb1c0192d989a26c/src/providers/accounts.tsx#L161
https://github.com/solana-labs/explorer/blob/82d5aa96354613e321152f32eb1c0192d989a26c/src/providers/accounts.tsx#L230
https://github.com/solana-labs/explorer/blob/82d5aa96354613e321152f32eb1c0192d989a26c/src/providers/transactions/index.tsx#L274

**Comment by nick-brown** [comment]
@jstarry got it, thanks!
