### ISSUE TITLE
Missing State field for TokenAccounts

### ISSUE THREAD

**Issue by tiago18c** [solana-labs/explorer#386]
When visiting the page for Token Accounts the state field is not displayed. This is an important field - both for users and devs. As tokenization picks up steam, this will be an evermore important piece of information.

Example from explorer: https://explorer.solana.com/address/yU1Se7d7hKqFfs1NijH6cirMYQBfALA2C5kn8XQ8ynG
Example from other explorer: https://solscan.io/account/yU1Se7d7hKqFfs1NijH6cirMYQBfALA2C5kn8XQ8ynG

The possible account states: 
- Token2022: https://github.com/solana-labs/solana-program-library/blob/master/token/program-2022/src/state.rs#L205-L217
- TokenKeg: https://github.com/solana-labs/solana-program-library/blob/master/token/program/src/state.rs#L187-L198

**Comment by ngundotra** [comment]
Fixed by #387
