### ISSUE TITLE
[feature request] Add bankhash to Solana explorer

### ISSUE THREAD

**Issue by 7layermagik** [solana-labs/explorer#391]
The bankhash is the final cryptographic stamp/identifier for blocks that have been agreed upon through consensus. It would be nice to have this in the explorer when referencing certain blocks

**Comment by ngundotra** [comment]
Hey @7layermagik  you can only get up to 512 of the last slots via Sysvar, so if you’re querying an older block it’s gotta be indexed. Doesn't seem like it's going to be added to RPC for now, so closing for time being.

If you really want this & get Triton or Helius to support it, then please reopen this issue 🙏
