### ISSUE TITLE
[Bug] request localhost:3000  failed http_code=500

### ISSUE THREAD

**Issue by 0xA2618** [solana-labs/explorer#400]
My steps are as follows
step1:
	git clone https://github.com/solana-labs/explorer.git
	cd explorer  
	pnpm i 

	npm dev 

step2:
	curl http://localhost:3000 

I get result  
...
GET / 500 in 8745ms
...

Attached are specific logs
[solana.err.log](https://github.com/user-attachments/files/17571055/solana.err.log)

**Comment by ngundotra** [comment]
Please upgrade your `pnpm` version to `9.10.0` or higher

Then reset your changes & restore the lockfile then re-install.
```shell
git stash
pnpm i
git stash pop
pnpm dev
```
