### ISSUE TITLE
Empty account balance should show as 0 instead of "Error"

### ISSUE THREAD

**Issue by mvines** [solana-labs/explorer#47]
![image](https://user-images.githubusercontent.com/1281082/78186267-4d6db680-7421-11ea-8571-2a8035632195.png)

but
```
$ solana balance vines1vzrYbzLMRdu58ou5XTby4qAqVRLmqo36NKPTg
0 SOL
```

**Comment by jstarry** [comment]
@mvines what do we want for DATA / OWNER?

**Comment by jstarry** [comment]
I guess 0 bytes, system account are reasonable defaults

**Comment by mvines** [comment]
`-`/`-` seems good.    data/owner is undefined for an account with 0 lamports
