### ISSUE TITLE
Nonce instructions aren't nicely displayed

### ISSUE THREAD

**Issue by mvines** [solana-labs/explorer#70]
Instruction #2 is a `InitializeNonceAccount`:
![image](https://user-images.githubusercontent.com/1281082/78960303-8271ad00-7aa2-11ea-988b-387e142662cf.png)

Instruction #1 is a `AdvanceNonceAccount`:
![image](https://user-images.githubusercontent.com/1281082/78960326-97e6d700-7aa2-11ea-9866-056aaca3c4c2.png)

**Comment by jstarry** [comment]
Fixed in https://github.com/solana-labs/explorer/pull/104
