### ISSUE TITLE
Circulating supply is not displayed

### ISSUE THREAD

**Issue by rajgokal** [solana-labs/explorer#71]
sum of all accounts that aren’t the community/foundation/grant wallets and aren’t stake accounts with lockups

**Comment by mvines** [comment]
We probably display the total and circulating supply for completeness.

Depends-on: https://github.com/solana-labs/solana/issues/9433

**Comment by jstarry** [comment]
@mvines is this still needed in the explorer? Right now explorer just serves static files but we could add a simple node api server to serve this info

**Comment by jstarry** [comment]
Closed by https://github.com/solana-labs/explorer/pull/131
