### ISSUE TITLE
Display historical transactions for an address

### ISSUE THREAD

**Issue by mvines** [solana-labs/explorer#72]
We recently added these two RPC APIs to serve this purpose:
* `getConfirmedSignaturesForAddres` - https://docs.solana.com/apps/jsonrpc-api#getconfirmedsignaturesforaddress
* `getConfirmedTransaction` - https://docs.solana.com/apps/jsonrpc-api#getconfirmedtransaction

**Comment by mvines** [comment]
cc: https://github.com/solana-labs/solana/pull/9614

**Comment by jstarry** [comment]
Closed by https://github.com/solana-labs/explorer/pull/77
